[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11" 
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
async-stream = "0.3"

# DIESER TEIL IST ENTSCHEIDEND
[build-dependencies]
tonic-build = "0.11" 