[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures-util = "0.3" 
async-stream = "0.3"
axum = "0.8.6"
hostname = "0.4.1"

[build-dependencies]
tonic-build = "0.11"
