[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11" 
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"
async-stream = "0.3"
dashmap = "6.1.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "sqlite", "postgres", "json"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
axum = { version = "0.8.6", features = ["ws"] } 
futures-util = "0.3.31"
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["v4"] }

# DIESER TEIL IST ENTSCHEIDEND
[build-dependencies]
tonic-build = "0.11" 
